import { ToastContainer } from "react-toastify";
import "./globals.css";
import ProviderNext from "@/store/Provider";
import "react-toastify/dist/ReactToastify.css";
import Detection from "@/Components/LoadModels";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProviderNext>
        <Detection>
          <body className={"page"}>
            {children}
            <ToastContainer />
          </body>
        </Detection>
      </ProviderNext>
    </html>
  );
}
