import dynamic from "next/dynamic";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import ProviderNext from "@/store/Provider";
import "react-toastify/dist/ReactToastify.css";
const Detection = dynamic(() => import("@/Components/LoadModels"));
import { Inter } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProviderNext>
        <Detection>
          <body className={inter.className}>
            {children}
            <ToastContainer />
          </body>
        </Detection>
      </ProviderNext>
    </html>
  );
}
